/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dutchconnected.fruithuis.frames;

import com.dutchconnected.fruithuis.Category;
import com.dutchconnected.fruithuis.Product;
import com.dutchconnected.fruithuis.ProductUnitUser;
import com.dutchconnected.fruithuis.Unit;
import java.awt.Graphics2D;
import java.awt.GridBagConstraints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author sha_y_000
 */
public class ProductFrame extends javax.swing.JPanel {

    private final Product product;

    /**
     * Creates new form Product
     * @param product
     */
    public ProductFrame(Product product) {
        this.product = product;
        initComponents();       
        for(ProductUnitUser price : product.getPrice()) {
            JLabel label = new JLabel();
            label.setText("€" + price.getPriceForAmountOfProduct(price.getMinAmount())
                    + " voor " + price.getMinAmount() + " per " + price.getUnitId().getSmall());
            GridBagConstraints gb = new GridBagConstraints();
            gb.gridx = 0;
            gb.anchor = GridBagConstraints.WEST;
            this.priceList.add(label, gb);
        }
        image.setIcon(new ImageIcon(product.getImage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        priceList = new javax.swing.JPanel();

        image.setBackground(new java.awt.Color(255, 102, 204));
        image.setOpaque(true);

        jLabel1.setText(product.getName());

        priceList.setMaximumSize(new java.awt.Dimension(200, 32767));
        priceList.setLayout(new java.awt.GridBagLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceList, javax.swing.GroupLayout.DEFAULT_SIZE, 5, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel priceList;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] arg) throws IOException {
        Product product = new Product();
        
        product.setId(1);
        product.setName("test");
        Set<ProductUnitUser> prices = new HashSet<>();
        prices.add(new ProductUnitUser(1, product, new Unit(1, "1000 gram", "1000 gram"), null, 10, 10, 1));
        prices.add(new ProductUnitUser(1, product, new Unit(1, "kg", "kg"), null, 10, 10, 1));
        product.setCategoryId(new Category(1, "test", new byte[0]));
        product.setPrice(prices);
        BufferedImage image = new BufferedImage(100, 100, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = (Graphics2D) image.getGraphics();
        try {
            g2.drawLine(0, 0, 100, 100);
        } finally {
            g2.dispose();
        }
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        ImageIO.write(image, "png", out);
        product.setImage(out.toByteArray());
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        frame.add(new ProductFrame(product));
        frame.pack();
        frame.setVisible(true);
    }
}
